package com.liferay.mobilephones.model.impl;

import com.liferay.mobilephones.model.MBMobilePhone;
import com.liferay.mobilephones.service.MBMobilePhoneLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MBMobilePhone service. Represents a row in the &quot;MB_MBMobilePhone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MBMobilePhoneImpl}.
 * </p>
 *
 * @author Leonardo Ribeiro
 * @see MBMobilePhoneImpl
 * @see com.liferay.mobilephones.model.MBMobilePhone
 * @generated
 */
public abstract class MBMobilePhoneBaseImpl extends MBMobilePhoneModelImpl
    implements MBMobilePhone {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a m b mobile phone model instance should use the {@link MBMobilePhone} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            MBMobilePhoneLocalServiceUtil.addMBMobilePhone(this);
        } else {
            MBMobilePhoneLocalServiceUtil.updateMBMobilePhone(this);
        }
    }
}
