package com.liferay.mobilephones.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.mobilephones.model.MBMobilePhone;
import com.liferay.mobilephones.service.MBMobilePhoneLocalService;
import com.liferay.mobilephones.service.persistence.MBMobilePhonePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the m b mobile phone local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.mobilephones.service.impl.MBMobilePhoneLocalServiceImpl}.
 * </p>
 *
 * @author Leonardo Ribeiro
 * @see com.liferay.mobilephones.service.impl.MBMobilePhoneLocalServiceImpl
 * @see com.liferay.mobilephones.service.MBMobilePhoneLocalServiceUtil
 * @generated
 */
public abstract class MBMobilePhoneLocalServiceBaseImpl
    extends BaseLocalServiceImpl implements MBMobilePhoneLocalService,
        IdentifiableBean {
    @BeanReference(type = MBMobilePhoneLocalService.class)
    protected MBMobilePhoneLocalService mbMobilePhoneLocalService;
    @BeanReference(type = MBMobilePhonePersistence.class)
    protected MBMobilePhonePersistence mbMobilePhonePersistence;
    @BeanReference(type = CounterLocalService.class)
    protected CounterLocalService counterLocalService;
    @BeanReference(type = ResourceLocalService.class)
    protected ResourceLocalService resourceLocalService;
    @BeanReference(type = ResourceService.class)
    protected ResourceService resourceService;
    @BeanReference(type = ResourcePersistence.class)
    protected ResourcePersistence resourcePersistence;
    @BeanReference(type = UserLocalService.class)
    protected UserLocalService userLocalService;
    @BeanReference(type = UserService.class)
    protected UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private MBMobilePhoneLocalServiceClpInvoker _clpInvoker = new MBMobilePhoneLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.mobilephones.service.MBMobilePhoneLocalServiceUtil} to access the m b mobile phone local service.
     */

    /**
     * Adds the m b mobile phone to the database. Also notifies the appropriate model listeners.
     *
     * @param mbMobilePhone the m b mobile phone
     * @return the m b mobile phone that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public MBMobilePhone addMBMobilePhone(MBMobilePhone mbMobilePhone)
        throws SystemException {
        mbMobilePhone.setNew(true);

        return mbMobilePhonePersistence.update(mbMobilePhone, false);
    }

    /**
     * Creates a new m b mobile phone with the primary key. Does not add the m b mobile phone to the database.
     *
     * @param id the primary key for the new m b mobile phone
     * @return the new m b mobile phone
     */
    public MBMobilePhone createMBMobilePhone(long id) {
        return mbMobilePhonePersistence.create(id);
    }

    /**
     * Deletes the m b mobile phone with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param id the primary key of the m b mobile phone
     * @return the m b mobile phone that was removed
     * @throws PortalException if a m b mobile phone with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public MBMobilePhone deleteMBMobilePhone(long id)
        throws PortalException, SystemException {
        return mbMobilePhonePersistence.remove(id);
    }

    /**
     * Deletes the m b mobile phone from the database. Also notifies the appropriate model listeners.
     *
     * @param mbMobilePhone the m b mobile phone
     * @return the m b mobile phone that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public MBMobilePhone deleteMBMobilePhone(MBMobilePhone mbMobilePhone)
        throws SystemException {
        return mbMobilePhonePersistence.remove(mbMobilePhone);
    }

    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(MBMobilePhone.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return mbMobilePhonePersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return mbMobilePhonePersistence.findWithDynamicQuery(dynamicQuery,
            start, end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return mbMobilePhonePersistence.findWithDynamicQuery(dynamicQuery,
            start, end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return mbMobilePhonePersistence.countWithDynamicQuery(dynamicQuery);
    }

    public MBMobilePhone fetchMBMobilePhone(long id) throws SystemException {
        return mbMobilePhonePersistence.fetchByPrimaryKey(id);
    }

    /**
     * Returns the m b mobile phone with the primary key.
     *
     * @param id the primary key of the m b mobile phone
     * @return the m b mobile phone
     * @throws PortalException if a m b mobile phone with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public MBMobilePhone getMBMobilePhone(long id)
        throws PortalException, SystemException {
        return mbMobilePhonePersistence.findByPrimaryKey(id);
    }

    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return mbMobilePhonePersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the m b mobile phones.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param start the lower bound of the range of m b mobile phones
     * @param end the upper bound of the range of m b mobile phones (not inclusive)
     * @return the range of m b mobile phones
     * @throws SystemException if a system exception occurred
     */
    public List<MBMobilePhone> getMBMobilePhones(int start, int end)
        throws SystemException {
        return mbMobilePhonePersistence.findAll(start, end);
    }

    /**
     * Returns the number of m b mobile phones.
     *
     * @return the number of m b mobile phones
     * @throws SystemException if a system exception occurred
     */
    public int getMBMobilePhonesCount() throws SystemException {
        return mbMobilePhonePersistence.countAll();
    }

    /**
     * Updates the m b mobile phone in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param mbMobilePhone the m b mobile phone
     * @return the m b mobile phone that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public MBMobilePhone updateMBMobilePhone(MBMobilePhone mbMobilePhone)
        throws SystemException {
        return updateMBMobilePhone(mbMobilePhone, true);
    }

    /**
     * Updates the m b mobile phone in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param mbMobilePhone the m b mobile phone
     * @param merge whether to merge the m b mobile phone with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
     * @return the m b mobile phone that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public MBMobilePhone updateMBMobilePhone(MBMobilePhone mbMobilePhone,
        boolean merge) throws SystemException {
        mbMobilePhone.setNew(false);

        return mbMobilePhonePersistence.update(mbMobilePhone, merge);
    }

    /**
     * Returns the m b mobile phone local service.
     *
     * @return the m b mobile phone local service
     */
    public MBMobilePhoneLocalService getMBMobilePhoneLocalService() {
        return mbMobilePhoneLocalService;
    }

    /**
     * Sets the m b mobile phone local service.
     *
     * @param mbMobilePhoneLocalService the m b mobile phone local service
     */
    public void setMBMobilePhoneLocalService(
        MBMobilePhoneLocalService mbMobilePhoneLocalService) {
        this.mbMobilePhoneLocalService = mbMobilePhoneLocalService;
    }

    /**
     * Returns the m b mobile phone persistence.
     *
     * @return the m b mobile phone persistence
     */
    public MBMobilePhonePersistence getMBMobilePhonePersistence() {
        return mbMobilePhonePersistence;
    }

    /**
     * Sets the m b mobile phone persistence.
     *
     * @param mbMobilePhonePersistence the m b mobile phone persistence
     */
    public void setMBMobilePhonePersistence(
        MBMobilePhonePersistence mbMobilePhonePersistence) {
        this.mbMobilePhonePersistence = mbMobilePhonePersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the resource remote service.
     *
     * @return the resource remote service
     */
    public ResourceService getResourceService() {
        return resourceService;
    }

    /**
     * Sets the resource remote service.
     *
     * @param resourceService the resource remote service
     */
    public void setResourceService(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * Returns the resource persistence.
     *
     * @return the resource persistence
     */
    public ResourcePersistence getResourcePersistence() {
        return resourcePersistence;
    }

    /**
     * Sets the resource persistence.
     *
     * @param resourcePersistence the resource persistence
     */
    public void setResourcePersistence(ResourcePersistence resourcePersistence) {
        this.resourcePersistence = resourcePersistence;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("com.liferay.mobilephones.model.MBMobilePhone",
            mbMobilePhoneLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.liferay.mobilephones.model.MBMobilePhone");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return MBMobilePhone.class;
    }

    protected String getModelClassName() {
        return MBMobilePhone.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = mbMobilePhonePersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
