package com.liferay.mobilephones.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MBMobilePhone service. Represents a row in the &quot;MB_MBMobilePhone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.mobilephones.model.impl.MBMobilePhoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.mobilephones.model.impl.MBMobilePhoneImpl}.
 * </p>
 *
 * @author Leonardo Ribeiro
 * @see MBMobilePhone
 * @see com.liferay.mobilephones.model.impl.MBMobilePhoneImpl
 * @see com.liferay.mobilephones.model.impl.MBMobilePhoneModelImpl
 * @generated
 */
public interface MBMobilePhoneModel extends BaseModel<MBMobilePhone> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a m b mobile phone model instance should use the {@link MBMobilePhone} interface instead.
     */

    /**
     * Returns the primary key of this m b mobile phone.
     *
     * @return the primary key of this m b mobile phone
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this m b mobile phone.
     *
     * @param primaryKey the primary key of this m b mobile phone
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this m b mobile phone.
     *
     * @return the ID of this m b mobile phone
     */
    public long getId();

    /**
     * Sets the ID of this m b mobile phone.
     *
     * @param id the ID of this m b mobile phone
     */
    public void setId(long id);

    /**
     * Returns the name of this m b mobile phone.
     *
     * @return the name of this m b mobile phone
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this m b mobile phone.
     *
     * @param name the name of this m b mobile phone
     */
    public void setName(String name);

    /**
     * Returns the brand of this m b mobile phone.
     *
     * @return the brand of this m b mobile phone
     */
    @AutoEscape
    public String getBrand();

    /**
     * Sets the brand of this m b mobile phone.
     *
     * @param brand the brand of this m b mobile phone
     */
    public void setBrand(String brand);

    /**
     * Returns the description of this m b mobile phone.
     *
     * @return the description of this m b mobile phone
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this m b mobile phone.
     *
     * @param description the description of this m b mobile phone
     */
    public void setDescription(String description);

    /**
     * Returns the release date of this m b mobile phone.
     *
     * @return the release date of this m b mobile phone
     */
    public Date getReleaseDate();

    /**
     * Sets the release date of this m b mobile phone.
     *
     * @param releaseDate the release date of this m b mobile phone
     */
    public void setReleaseDate(Date releaseDate);

    /**
     * Returns the price of this m b mobile phone.
     *
     * @return the price of this m b mobile phone
     */
    public double getPrice();

    /**
     * Sets the price of this m b mobile phone.
     *
     * @param price the price of this m b mobile phone
     */
    public void setPrice(double price);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(MBMobilePhone mbMobilePhone);

    public int hashCode();

    public CacheModel<MBMobilePhone> toCacheModel();

    public MBMobilePhone toEscapedModel();

    public MBMobilePhone toUnescapedModel();

    public String toString();

    public String toXmlString();
}
